# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for BSR Merchant Reconciliation Tool."""

import os

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets', 'assets'),
        ('config', 'config'),
    ],
    hiddenimports=[
        'PyQt6.QtWidgets',
        'PyQt6.QtGui',
        'PyQt6.QtCore',
        'pandas',
        'pandas._libs',
        'pandas._libs.tslibs',
        'pandas._libs.tslibs.timedeltas',
        'pandas._libs.tslibs.nattype',
        'pandas._libs.tslibs.np_datetime',
        'pandas.core.arrays.masked',
        'openpyxl',
        'openpyxl.styles',
        'openpyxl.utils',
        'openpyxl.cell',
        'openpyxl.workbook',
        'openpyxl.worksheet',
        'numpy',
        'numpy._core',
        'anthropic',
        'json',
        'csv',
        'shutil',
        'pathlib',
        'datetime',
        'itertools',
        're',
        'core',
        'core.config',
        'core.parsers',
        'core.updater',
        'core.reconciler',
        'core.anomalies',
        'core.ai_analyst',
        'core.file_detector',
        'config',
        'parsers',
        'parsers.types',
        'parsers.karibu_ledger_csv',
        'parsers.mtn_merchant_csv',
        'parsers.airtel_merchant_csv',
        'parsers.momo_agent_xlsx',
        'yaml',
        'ui',
        'ui.main_window',
        'ui.settings_dialog',
        'ui.upload_panel',
        'utils',
        'utils.backup',
        'utils.excel_writer',
        'workers',
        'workers.qt_workers',
        'workers.upload_worker',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'scipy',
        'PIL',
        'tkinter',
        'wx',
        'gtk',
        'IPython',
        'jupyter',
        'notebook',
        'pytest',
        'test',
        'unittest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='BSR_Recon',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.png',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='BSR_Recon',
)
